name: rx_command
description: Reactive event handler wrapper class inspired by ReactiveUI.
version: 6.1.0
maintainer: Thomas Burkhart (@escamoteur)
homepage: https://github.com/fluttercommunity/rx_command
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  rxdart: ^0.28.0
  quiver: ^3.0.1


dev_dependencies:
  test: any
